# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_stuff(object):
    def setupUi(self, note):
        note.setObjectName("Add Stuff")
        note.resize(403, 186)
        note.setMinimumSize(QtCore.QSize(403, 186))
        note.setMaximumSize(QtCore.QSize(403, 186))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/hiclipart.com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        note.setWindowIcon(icon)
        note.setSizeGripEnabled(False)
        note.setModal(False)
        self.label = QtWidgets.QLabel(note)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(note)
        self.lineEdit.setGeometry(QtCore.QRect(210, 50, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(note)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 90, 171, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(note)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(note)
        self.label_3.setGeometry(QtCore.QRect(60, 100, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(note)
        self.pushButton.setGeometry(QtCore.QRect(110, 142, 161, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(note)
        QtCore.QMetaObject.connectSlotsByName(note)

    def check_line(self):
        self.t1 = self.lineEdit.text()
        self.t2 = self.lineEdit_2.text()
     #   print(self.t1, self.t2)
        if (self.t1!='' and self.t2!='' ):
            return(self.t1 , self.t2)
        else : 
            return(-1 , -1)

    def retranslateUi(self, note):
        _translate = QtCore.QCoreApplication.translate
        note.setWindowTitle(_translate("note", "Add Stuff"))
        self.label.setText(_translate("note", "!!! If you complete both boxes it isn\'t be will be add !!!"))
        self.label_2.setText(_translate("note", "Stuff name :"))
        self.label_3.setText(_translate("note", "Stuff code :"))
        self.pushButton.setText(_translate("note", "Add to list"))



